---

language: python  # host language doesn't matter / not-used here
python:
    - 3.6

sudo: required

services:
  - docker

env:
    matrix:
        - DISTRO="ubuntu"
        - DISTRO="fedora"
        - DISTRO="centos"

    global:
        - CI_SCRIPT="/bin/true"  # Path + args for your CI script goes here

before_install:
  - sudo apt-get -qq update  # on the host
  - sudo apt-get -qq install realpath  # WTF this isn't part of the core?
  # Note: In this context (this this repository), there's a catch-22:
  # We can't rely on docker's auto-builds for testing purposes, because
  # they occur only _after_ a merge.  If re-using this .travis.yml for any
  # other repo, you can leave out the following two docker build commands.
  - sudo docker build -f venv_${DISTRO}.dockerfile -t docker.io/cevich/venv_${DISTRO}.dockerfile ./
  - sudo docker build -f travis_${DISTRO}.dockerfile -t docker.io/cevich/travis_${DISTRO}.dockerfile ./

script: "./travis.sh $CI_SCRIPT"
