---

language: generic

sudo: required

services:
  - docker

# Don't build my own PR branches
branches:
  only:
    - master

env:
    global:
        - VENV_SPC_CMD="ansible-doc --list"
        - TRAVIS_SPC_CMD="make --version"
    matrix:
        # Ubuntu
        - FQIN_SFX="ubuntu"
          FQIN_PFX="venv"
          SPC_CMD="$VENV_SPC_CMD"
        - FQIN_SFX="ubuntu"
          FQIN_PFX="travis"
          SPC_CMD="$TRAVIS_SPC_CMD"
        # Fedora
        - FQIN_SFX="fedora"
          FQIN_PFX="venv"
          SPC_CMD="$VENV_SPC_CMD"
        - FQIN_SFX="fedora"
          FQIN_PFX="travis"
          SPC_CMD="$TRAVIS_SPC_CMD"
        # CentOS
        - FQIN_SFX="centos"
          FQIN_PFX="venv"
          SPC_CMD="$VENV_SPC_CMD"
        - FQIN_SFX="centos"
          FQIN_PFX="travis"
          SPC_CMD="$TRAVIS_SPC_CMD"
        # Gcloud
        - FQIN_SFX="centos"
          FQIN_PFX="gcloud"
        # Gsutil
        - FQIN_SFX="centos"
          FQIN_PFX="gsutil"
        # Special purpose
        - FQIN_SFX="rhsm"
          FQIN_PFX="test"
          SPC_CMD="subscription-manager clean"

before_install:
  - sudo apt-get -qq update  # on the host
  - sudo apt-get -qq install realpath

install:
  - "./build.sh"

script:
  - "./test.sh"

after_success:
  - "./deploy.sh"
