---

language: generic

sudo: required

services:
  - docker

# Don't build my own PR branches
branches:
  only:
    - master

env:
    global:
        - VENV_SPC_CMD="ansible-doc --list
        - TRAVIS_SPC_CMD="make --version"
    matrix:
        # Ubuntu
        - FQIN_SFX="ubuntu"
          FQIN_PFX="venv"
          SPC_CMD="$VENV_SPC_CMD"
          TOKEN="$VENV_UBUNTU_TOKEN"
        - FQIN_SFX="ubuntu"
          FQIN_PFX="travis"
          SPC_CMD="$TRAVIS_SPC_CMD"
          TOKEN="$TRAVIS_UBUNTU_TOKEN"
        # Fedora
        - FQIN_SFX="fedora"
          FQIN_PFX="venv"
          SPC_CMD="$VENV_SPC_CMD"
          TOKEN="$VENV_FEDORA_TOKEN"
        - FQIN_SFX="fedora"
          FQIN_PFX="travis"
          SPC_CMD="$TRAVIS_SPC_CMD"
          TOKEN="$TRAVIS_FEDORA_TOKEN"
        # CentOS
        - FQIN_SFX="centos"
          FQIN_PFX="venv"
          SPC_CMD="$VENV_SPC_CMD"
          TOKEN="$VENV_CENTOS_TOKEN"
        - FQIN_SFX="centos"
          FQIN_PFX="travis"
          SPC_CMD="$TRAVIS_SPC_CMD"
          TOKEN="$TRAVIS_CENTOS_TOKEN"

before_install:
  - sudo apt-get -qq update  # on the host

install:
  - "./build.sh"

script:
  - "./test.sh"

after_success:
  - "./deploy.sh"
